In [1]:
import numpy as np

In [2]:
##--------------------------##
## --------创建数组----------##
##--------------------------##

In [3]:
#创建一个一维数组
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
#数组中的数据类型是一致的，若不一致会自动转换
np.array([1.1,2.2,3,4,5])

array([1.1, 2.2, 3. , 4. , 5. ])

In [5]:
#，也可以通过dtype指定数组类型
np.array([1,2,3,3],dtype = "float64")

array([1., 2., 3., 3.])

In [6]:
#创建多维数组
np.array([[1,2,3],
        [4,4,5],
        [7,7,7]])

array([[1, 2, 3],
       [4, 4, 5],
       [7, 7, 7]])

In [7]:
##使用numopy内置方法创建数组

In [8]:
#创建全部由0组成的数组
np.zeros((5,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
#创建全部由1组成的数组
np.ones(12,dtype= int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
#创建一个由3.14组成的3*5的矩阵
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
#创建一个由0开始，20结束，步长为2的数组
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#创建一个由五个元素组成的数据，这五个元素均匀分配到0到1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
#创建一个3×3的、 在0~1均匀分布的随机数组成的数组
np.random.random((3,3))

array([[0.44009512, 0.53067799, 0.33579672],
       [0.49724615, 0.45344011, 0.04823392],
       [0.24486555, 0.02649994, 0.4990224 ]])

In [14]:
#创建一个正态分布的数组
np.random.normal(0,1,(3,3))

array([[-1.00701813,  0.37689624, -1.04542478],
       [-0.42679256, -0.8316562 , -1.4927451 ],
       [ 0.25965431,  1.02822073, -1.36007402]])

In [15]:
#创建一个3*3 在[0,10)区间内的随机整数
np.random.randint(0,10,(3,3))

array([[2, 5, 8],
       [6, 8, 1],
       [5, 0, 9]])

In [16]:
#创建一个单位矩阵（必须为方阵）
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
 # 创建一个由3个整型数组成的未初始化的数组
    # 数组的值是内存空间中的任意值
np.empty(3)

array([0., 0., 0.])

In [18]:
##--------------------------##
## --------数组的属性--------##
##--------------------------##

In [19]:
#每个数据有四个主要属性， nidm（数组的维度）、shape（数组每个维度的大小） 、dtype和 size（数组的总大小） 

In [20]:
#设置一个数组
ay=np.random.randint(10,size =(3,4,5))
print(ay)

[[[2 0 9 2 6]
  [8 3 3 0 1]
  [3 9 7 5 8]
  [8 1 9 4 6]]

 [[5 3 0 6 3]
  [9 6 0 7 8]
  [7 9 4 4 7]
  [6 2 4 2 8]]

 [[6 9 7 1 4]
  [6 4 8 7 3]
  [1 7 6 6 5]
  [1 2 4 4 1]]]


In [21]:
#查看数组的属性
print(ay.ndim)
print(ay.shape)
print(ay.size)
print(ay.dtype)

3
(3, 4, 5)
60
int32


In [22]:
##--------------------------##
## -----数组的索引与切片-----##
##-------------------------##
#存疑

In [23]:
#创建一个一维数组,使用[]进行索引，与python类似，索引从0开始，只是负索引
ar0=np.array([1,2,3,4])

In [24]:
print(ar0[0])
print(ar0[1])
print(ar0[-1])
print(ar0[-2])

1
2
4
3


In [98]:
np.random.seed(123)
#创建一个多维度数组
ar1=np.random.randint(10,size =(3,3,4))
ar1

array([[[2, 2, 6, 1],
        [3, 9, 6, 1],
        [0, 1, 9, 0]],

       [[0, 9, 3, 4],
        [0, 0, 4, 1],
        [7, 3, 2, 4]],

       [[7, 2, 4, 8],
        [0, 7, 9, 3],
        [4, 6, 1, 5]]])

In [28]:
#可以逗号分隔的索引元组获取元素
print("index1: ","\n",ar1[0])
print("index2: ","\n",ar1[0,2])
print("index3: ","\n",ar1[0,2,-1])

index1:  
 [[2 2 6 1]
 [3 9 6 1]
 [0 1 9 0]]
index2:  
 [0 1 9 0]
index3:  
 0


In [29]:
#也可以用以上索引方式修改元素值,由于数组为整型所以插入的数据会被自动转换为整型，不会提示
ar1[0,2,-1]=999.999
print("index3: ","\n",ar1[0,2,-1])

index3:  
 999


In [30]:
#一维数组的切片
#创建一个一维数组
ar3=np.random.randint(10,size = 10)
print(ar3)

[6 2 1 8 3 5 0 2 6 2]


In [39]:
#array[start:stop:sep]:开始:结束:步长，默认最后一个元素是不被包含的类似于 [）
#从第0个元素开始取到第二个元素
print(ar3[0:3:1])

#倒序取出奇数index元素
print(ar3[::-2])

#按照倒序输出元素
print(ar3[::-1])

#前三个元素，步长为2
print(ar3[:4:2])

[6 2 1]
[2 2 5 8 2]
[2 6 2 0 5 3 8 1 2 6]
[6 1]


In [59]:
#多维度数组的切片
ar4=np.array([[12, 5, 2, 4],
           [ 7, 6, 8, 8],
           [ 1, 6, 7, 7]])
print(ar4)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [62]:
#[start:stop:sep]:开始:结束:步长，默认最后一个元素是不被包含的类似于 [）
print(ar4[1:3,1:3])
print("\n",ar4[:2,::3])

[[6 8]
 [6 7]]

 [[12  4]
 [ 7  8]]


In [85]:
##-------------------------##
## -------数组的变形--------##
##-------------------------##
#numpy数组可以通过调用reshape方法变行，如将1-9放入3*3的矩阵
ar5=np.arange(1,10).reshape((3,3))
print(ar5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
#将一个一维数组转变为二维的行或列的矩阵
ar4=np.array([[12, 5, 2, 4],
           [ 7, 6, 8, 8],
           [ 1, 6, 7, 7]]).reshape((4,3))
print(ar4)

[[12  5  2]
 [ 4  7  6]
 [ 8  8  1]
 [ 6  7  7]]


In [31]:
ar4[np.newaxis,:]

array([[[12,  5,  2],
        [ 4,  7,  6],
        [ 8,  8,  1],
        [ 6,  7,  7]]])

In [32]:
ar4[:, np.newaxis]

array([[[12,  5,  2]],

       [[ 4,  7,  6]],

       [[ 8,  8,  1]],

       [[ 6,  7,  7]]])

In [35]:
##-------------------------##
## -------拼接和拆分--------##
##-------------------------##

In [36]:
#将多个数组合并为一个， 或将一个数组分裂成多个
#np.concatenate、 np.vstack 和 np.hstack 
#连接数组
x = np.array([1,2,3,3,4])
y = np.array([5,6,7,8,9])
z = np.array([10,11,12])
np.concatenate((x,z))

array([ 1,  2,  3,  3,  4, 10, 11, 12])

In [37]:
#同时连接多个数组
np.concatenate((x,y,z))

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
#二维数组的拼接
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [39]:
#沿第0(1)轴拼接, 类似rbind
np.concatenate((grid,grid),axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
#沿第1(2)轴拼接，类似cbind
np.concatenate((grid,grid),axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
#沿着固定维度处理数组时， 使用 np.vstack（垂直栈）(rbind) 和 np.hstack（水平栈） (cbind)
x = np.array([[1, 2, 3],
              [6, 8, 8]])

grid = np.array([[9, 8, 7],
                 [6, 5, 4]])    

In [42]:
np.vstack((x,grid))

array([[1, 2, 3],
       [6, 8, 8],
       [9, 8, 7],
       [6, 5, 4]])

In [43]:
np.hstack((x,grid))

array([[1, 2, 3, 9, 8, 7],
       [6, 8, 8, 6, 5, 4]])

In [44]:
#数组的分裂
#通过np.split、 np.hsplit 和 np.vsplit 函数来实现

In [45]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [46]:
#3和5位分离的索引点
#分裂点为3时，[1,2,3]
#第一个99和第二个99位3 4
#最后一个3为5
#N 分裂点会得到 N + 1 个子数组
np.split(x,(3,5))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [47]:
#np.hsplit 和 np.vsplit 函数
grid=np.arange(9).reshape(3,3)
grid

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
np.split(grid,(1,2),axis = 0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [49]:
np.split(grid,(1,2),axis = 1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [50]:
np.vsplit(grid,(1,2))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [51]:
np.hsplit(grid,(1,2))

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]