In [3]:
import numpy as np
#NumPy 为很多类型的操作提供了非常方便的、 静态类型的、 可编译程序的接口， 也被称作向量操作。 你可以通过简单地对数组执行操作来实现，
#这里对数组的操作将会被用于数组中的每一个元素。 这种向量方法被用于将循环推送至 NumPy 之下的编译层， 这样会取得更快的执行效率

In [4]:
##-----------------------------##
##----------数组的运算----------##
##-----------------------------##

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# + - * / %% ....均可直接使用

In [7]:
print("+： ",x + 10)
print("-： ",x - 10)
print("*： ",x * 10)
print("/： ",x / 10)
print("%： ",x % 3)
print("//：",x // 3)#向下整除的值，如7//3 向下整除 即为 6//3 = 2
print("**：",x ** 3)
print("abs:",abs(x))

+：  [10 11 12 13 14 15 16 17 18 19]
-：  [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
*：  [ 0 10 20 30 40 50 60 70 80 90]
/：  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
%：  [0 1 2 0 1 2 0 1 2 0]
//： [0 0 0 1 1 1 2 2 2 3]
**： [  0   1   8  27  64 125 216 343 512 729]
abs: [0 1 2 3 4 5 6 7 8 9]


In [8]:
#指数和对数计算
x=np.arange(5)
print("指数运算")
print("e^x",np.exp(x))
print("2^x",np.power(2,x))
print("3^x",np.power(3,x))
print("\n","对数运算")
print("log10(x+1): ",np.log10(x + 1))
print("log2(x+1): ",np.log2(x + 1))

指数运算
e^x [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
2^x [ 1  2  4  8 16]
3^x [ 1  3  9 27 81]

 对数运算
log10(x+1):  [0.         0.30103    0.47712125 0.60205999 0.69897   ]
log2(x+1):  [0.         1.         1.5849625  2.         2.32192809]


In [9]:
#最大值，最小值，均值....的计算
x=np.random.randint(0,10,(1,10))
x

array([[4, 2, 6, 8, 0, 2, 0, 6, 9, 6]])

In [10]:
#数据求和
np.sum(x)

43

In [11]:
#最大值
np.max(x)

9

In [12]:
#最小值
np.min(x)

0

In [13]:
#平均值
np.mean(x)

4.3

In [14]:
#标准差
np.std(x)

3.034798181098704

In [15]:
#多维度数据的计算
x=np.random.randint(0,10,(3,3))
x

array([[2, 6, 6],
       [0, 8, 3],
       [0, 0, 2]])

In [16]:
#需要通过axis的值指定方向, 垂直方向
np.sum(x,axis=0)

array([ 2, 14, 11])

In [17]:
#水平方向
np.sum(x,axis=1)

array([14, 11,  2])

In [18]:
####----不同大小的数组运算-----####

In [19]:
#前一节中介绍了 NumPy 如何通过通用函数的向量化操作来减少缓慢的 Python 循环， 另外一种向量化操作的方法是利用 NumPy 的广播
#功能。 广播可以简单理解为用于不同大小数组的二进制通用函数（加、 减、 乘等） 的一组规则。

In [20]:
a = np.array([0,1,2])
b = np.array([5,5,5])
a + b

array([5, 6, 7])

In [21]:
#用于不同大小的数组。 
#例如， 可以简单地将一个标量（可以认为是一个零维的数组） 和一个数组相加：

In [22]:
#可以认为这个操作是将数值 5 扩展或重复至数组 [5, 5, 5]， 然后执行加法。 
a + 5

array([5, 6, 7])

In [23]:
#高维数组运算
a1 = np.arange(1,16).reshape((3,5))
a2 = np.ones((3,5),dtype=int)
print(a1)
print("\n",a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [24]:
#同纬度的高维数组相加
a1 + a2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [25]:
#不同维度
a3 = np.ones(5)
a3

array([1., 1., 1., 1., 1.])

In [26]:
a1 + a3

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.]])

In [27]:
a4 = 1
a1 + a4

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [28]:
#不同数组相加，相加的数组的某个维度要和被加的相等

In [29]:
a5 = np.ones(3)[:,np.newaxis]
a5

array([[1.],
       [1.],
       [1.]])

In [30]:
a1 + a5

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.]])

In [31]:
a6 = np.ones(5)[np.newaxis,:]
a6

array([[1., 1., 1., 1., 1.]])

In [32]:
a1 + a6

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.]])

In [33]:
a7 = np.arange(6).reshape(3,2)
a7
#无法相加，以为无法匹配维度

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
#三个规则
#规则 1： 如果两个数组的维度数不相同， 那么小维度数组的形状将会在最左边补 1。
#规则 2： 如果两个数组的形状在任何一个维度上都不匹配， 那么数组的形状会沿着维度为 1 的维度扩展以匹配另外一个数组的形状。
#规则 3： 如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于 1， 那么会引发异常。

In [35]:
#常见应用
#数组的标准化
x = np.random.random((10, 3))
x

array([[0.19927251, 0.52175016, 0.06235894],
       [0.41975503, 0.72267562, 0.34466395],
       [0.02893029, 0.62294777, 0.20718657],
       [0.64028828, 0.88155318, 0.24574171],
       [0.2001945 , 0.27627994, 0.57157932],
       [0.64960346, 0.09962495, 0.73804043],
       [0.89543081, 0.52009981, 0.37979536],
       [0.27562113, 0.0032048 , 0.79537271],
       [0.53979742, 0.93055993, 0.98398222],
       [0.89458649, 0.89245308, 0.44014415]])

In [36]:
#对每列标准化
means = np.mean(x,axis= 0)
sd = np.std(x,axis=0)
print("mean: ",means)
print("sd: ",sd)

mean:  [0.47434799 0.54711492 0.47688654]
sd:  [0.28427834 0.31392991 0.2760446 ]


In [37]:
#标准化
x_scale = (x -means) / sd
x_scale

array([[-0.96762727, -0.08079753, -1.50166893],
       [-0.19204051,  0.55923532, -0.47898996],
       [-1.56683658,  0.24155979, -0.97701591],
       [ 0.58372469,  1.06532777, -0.83734594],
       [-0.96438401, -0.86272435,  0.34303436],
       [ 0.61649249, -1.42544547,  0.94605688],
       [ 1.48123425, -0.08605461, -0.35172278],
       [-0.69905733, -1.73258456,  1.15374899],
       [ 0.23023008,  1.22143506,  1.83700638],
       [ 1.4782642 ,  1.10004858, -0.13310309]])

In [38]:
np.sum(x_scale,axis=0)

array([2.66453526e-15, 4.44089210e-16, 1.22124533e-15])

In [39]:
## 比较运算
#NumPy 还实现了如 <（小于） 和 >（大于） 的逐元素比较的通用函数。 这些比较运算的结果是一个布尔数据类型的数组。 一共有 6 种标准的比较操作

In [40]:
x = np.array([1, 2, 3, 4, 5])
print(x > 3)
print(x < 3)
print(x >= 3)
print(x <= 3)
print(x == 3)
print(x != 3)

[False False False  True  True]
[ True  True False False False]
[False False  True  True  True]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


In [41]:
#复合比较也是从可以的
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [42]:
#运算符号与numpy内部函数对应表
#== np.equal
#!= np.not_equal
#< np.less
#<= np.less_equal
#> np.greater 
#>= np.greater_equal

In [43]:
#统计比较结果
x2 = np.arange(15).reshape((3,5))
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
#统计有多少值小于6？

In [45]:
#方法1，原理，Ture为1 False为0 和R一样
#对列统计
print(np.count_nonzero(x2 < 6,axis=0))
#对行统计
print(np.count_nonzero(x2 <6,axis = 1))
#全部统计
print(np.count_nonzero(x2 < 6))

[2 1 1 1 1]
[5 1 0]
6


In [46]:
#方法2，原理，Ture为1 False为0 和R一样
#对列统计
print(np.sum(x2 < 6,axis=0))
#对行统计
print(np.sum(x2 <6,axis = 1))
#全部统计
print(np.sum(x2 < 6))

[2 1 1 1 1]
[5 1 0]
6


In [47]:
#快速检查任意或者所有这些值是否为 True,np.all() np.any()
#np.any 同样可以指定行列，axis=0 返回值为检查每列是否存在大于6的值
np.any(x2 > 6,axis=0)

array([ True,  True,  True,  True,  True])

In [48]:
#np.all()检查是否都大于某个数，同样可以指定行列
np.all(x2 > 6,axis = 0)

array([False, False, False, False, False])

In [49]:
#逻辑运算符
#& ^ | ...
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
#&
(x2 > 2) & (x2 < 6)
np.sum(((x2 > 2) & (x2 < 6)),axis=0)

array([1, 0, 0, 1, 1])

In [51]:
#|
(x2 > 2) | (x2 < 6)
np.sum(((x2 > 2) | (x2 < 6)),axis=0)

array([3, 3, 3, 3, 3])

In [52]:
#数据索引
x2[x2 > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
x2[(x2 > 2) & (x < 5)]

array([ 3,  5,  6,  7,  8, 10, 11, 12, 13])

In [54]:
x2[(x2 > 2) | (x < 5)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
#复杂索引：意味着传递一个索引数组来一次性获得多个数组元素
y=np.random.randint(0,100,10)
y

array([17, 61, 56, 15, 71,  2, 23, 45, 68, 96])

In [62]:
#获得三个不同的元素
[y[2],y[8],y[-3]]

[56, 68, 45]

In [67]:
print(y[[2,8,-3]])
#或者将[2,8,-3]赋给一个变量
dd=[2,8,-3]
print(y[dd])

[56 68 45]
[56 68 45]


In [69]:
#结果的形状与索引数组的形状一致， 而不是与被索引数组的形状一致
ind = np.array([[3, 7],
                [4, 5]])
y[ind]

array([[15, 45],
       [71,  2]])

In [70]:
#对多个维度进行索引时
y2 = np.arange(12).reshape((3, 4))
y2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
y2[row, col]
#第0行的第二个元素，第1行的第一个元素，第二行的第三个元素
#结果的第一个值是 y[0, 2]， 第二个值是 y[1, 1]， 第三个值是 y[2, 3]。 

array([ 2,  5, 11])