In [4]:
##-----------------------------##
##----------数组的排序----------##
##-----------------------------##

In [5]:
import numpy as np
#NumPy中的快速排序： np.sort和np.argsort

In [6]:
x = np.array([2, 1, 4, 3, 5])

In [8]:
#对数组进行排序np.sort
np.sort(x)

array([1, 2, 3, 4, 5])

In [10]:
#对数组排序，np.argsort 返回值为数组的索引值
print(np.argsort(x))
#可以使用其返回结果直接创建有序数组
print(x[np.argsort(x)])

[1 0 3 2 4]
[1 2 3 4 5]


In [16]:
#沿着行或列排序
x1 = np.random.randint(1,20,20).reshape((4,5))
x1

array([[ 5,  9, 16, 11, 10],
       [13,  7,  9, 14,  6],
       [ 4, 11,  6,  8,  9],
       [ 9, 11,  6, 14, 17]])

In [17]:
#按照列排序
np.sort(x1,axis=0)

array([[ 4,  7,  6,  8,  6],
       [ 5,  9,  6, 11,  9],
       [ 9, 11,  9, 14, 10],
       [13, 11, 16, 14, 17]])

In [18]:
#按照行排序
np.sort(x1,axis=1)

array([[ 5,  9, 10, 11, 16],
       [ 6,  7,  9, 13, 14],
       [ 4,  6,  8,  9, 11],
       [ 6,  9, 11, 14, 17]])

In [19]:
#分隔排序，不对整个数组进行排序， 仅仅希望找到数组中前 K 小的值
x2 = np.array([7, 2, 3, 1, 6, 5, 4])
x2

array([7, 2, 3, 1, 6, 5, 4])

In [21]:
#np.partition提供了这一功能，
#结果数组中前三个值是数组中最小的三个值， 剩下的位置是原始数组剩下的值。 在这两个分隔区间中，元素都是任意排列的。
#与排序类似， 也可以沿着多维数组任意的轴进行分隔
np.partition(x2,4)

array([2, 1, 3, 4, 5, 6, 7])

In [24]:
x3 = np.random.randint(1,100,25).reshape(5,5)
x3

array([[13,  3, 64, 89, 67],
       [13,  5, 10, 55,  8],
       [72, 41, 97, 15, 48],
       [53, 62, 17, 50, 72],
       [41, 94, 46, 99, 45]])

In [25]:
#对行操作
np.partition(x3,3,axis=1)

array([[ 3, 13, 64, 67, 89],
       [ 5,  8, 10, 13, 55],
       [15, 48, 41, 72, 97],
       [50, 17, 53, 62, 72],
       [41, 45, 46, 94, 99]])

In [26]:
#对列操作(默认)
np.partition(x3,3,axis = 0)

array([[13,  5, 17, 50,  8],
       [13,  3, 46, 15, 45],
       [41, 41, 10, 55, 48],
       [53, 62, 64, 89, 67],
       [72, 94, 97, 99, 72]])

In [29]:
#np.argpartition可以返回分隔排序的索引值
np.argpartition(x3,3,axis=0)

array([[1, 1, 3, 3, 1],
       [0, 0, 4, 2, 4],
       [4, 2, 1, 1, 2],
       [3, 3, 0, 0, 0],
       [2, 4, 2, 4, 3]], dtype=int32)

In [30]:
np.argpartition(x3,3,axis=1)

array([[1, 0, 2, 4, 3],
       [1, 4, 2, 0, 3],
       [3, 4, 1, 0, 2],
       [3, 2, 0, 1, 4],
       [0, 4, 2, 1, 3]], dtype=int32)

In [34]:
#同时也可以生成有序数组,每行对应一个索引，所以每个索引会生成5行数据
x3[np.argpartition(x3,3,axis = 1)]

array([[[13,  5, 10, 55,  8],
        [13,  3, 64, 89, 67],
        [72, 41, 97, 15, 48],
        [41, 94, 46, 99, 45],
        [53, 62, 17, 50, 72]],

       [[13,  5, 10, 55,  8],
        [41, 94, 46, 99, 45],
        [72, 41, 97, 15, 48],
        [13,  3, 64, 89, 67],
        [53, 62, 17, 50, 72]],

       [[53, 62, 17, 50, 72],
        [41, 94, 46, 99, 45],
        [13,  5, 10, 55,  8],
        [13,  3, 64, 89, 67],
        [72, 41, 97, 15, 48]],

       [[53, 62, 17, 50, 72],
        [72, 41, 97, 15, 48],
        [13,  3, 64, 89, 67],
        [13,  5, 10, 55,  8],
        [41, 94, 46, 99, 45]],

       [[13,  3, 64, 89, 67],
        [41, 94, 46, 99, 45],
        [72, 41, 97, 15, 48],
        [13,  5, 10, 55,  8],
        [53, 62, 17, 50, 72]]])